DjangoFileUpload/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home" ) ,
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('fileUpload/', include('Upload.urls', namespace='Upload'))
]

Upload/urls.py
from django.urls import path
from . import views

app_name = "Upload"
urlpatterns = [
    path('', views.upload_file, name='fileUpload'),
    path("files/", views.all_files, name="all_files"),
    path("download/<int:file_id>", views.download_file, name="download_file")
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [

    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name="logout")
    
]

Upload/models.py
from django.db import models

# Create your models here.
class Files(models.Model):
    files = models.FileField(upload_to="uploads/")

accounts/models.py
from django.db import models

# Create your models here.

Upload/forms.py
from django import forms

class UploadFileForm(forms.Form):
    files = forms.FileField()

accounts/forms.py
from django import forms



class UserRegistration(forms.Form):

    username = forms.CharField(label="Username", max_length=10, min_length=5,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    
    email = forms.EmailField(label="Email", max_length=20, min_length=10,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))
    
    password = forms.CharField(label="Password", max_length=20, min_length=8,
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    
    renter_password = forms.CharField(label="Renter Password", max_length=20, min_length=8,
                                    widget=forms.PasswordInput(attrs={'class': 'form-control'}))

DjangoFileUpload/views.py
from django.shortcuts import render,redirect    
from django.contrib.auth.decorators import login_required

def home(request):
    return redirect('accounts:login')

Upload/views.py
from django.shortcuts import render, redirect
from .forms import UploadFileForm
from django.http import HttpResponse
from .models import Files
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required()
def upload_file(request):

    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            ufile = request.FILES['files']
            uploadedFile = Files.objects.create(files=ufile)
            uploadedFile.save()

            return redirect('Upload:all_files')
    
    else:

        form = UploadFileForm()

    return render(request, 'FileUpload.html', {'form':form})

@login_required()
def all_files(request):
    files = Files.objects.all()
    return render(request, 'all_files.html', {'files':files})

@login_required()
def download_file(request, file_id):
    uploaded_file = Files.objects.get(pk=file_id)
    response = HttpResponse(uploaded_file.files, content_type='application/force-download')
    response['Content-Disposition'] = f'attachment; filename="{uploaded_file.files.name}"'
    return response

accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserRegistration
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import login,logout,authenticate
# Create your views here.


def logout_user(request):
    logout(request)
    return redirect('accounts:login')

def register_user(request):

    if request.method == 'POST':
        check1=False
        check2=False
        check3=False

        form = UserRegistration(request.POST)
        if form.is_valid():

            username = form.cleaned_data['username']
            password1 = form.cleaned_data['password']
            password2 = form.cleaned_data['renter_password']
            email = form.cleaned_data['email']

            if password1!=password2:
                check1 = True
                messages.error(request,'Password doesnt match!',
                                extra_tags='alert alert-warning alert-dismissible fade show ')

            if User.objects.filter(email=email).exists():
                check2 = True
                messages.error(request,'Email already exists!',
                                extra_tags='alert alert-warning alert-dismissible fade show ')

            if User.objects.filter(username=username).exists():
                check3 = True
                messages.error(request,'Username already exists!',
                                extra_tags='alert alert-warning alert-dismissible fade show ')
            
            if check1 or check2 or check3:

                messages.error(request,'Registration failed!',
                               extra_tags='alert alert-warning alert-dismissible fade show')

                return redirect('accounts:register')
            
            else:
                user=User.objects.create_user(username=username,password=password1,email=email)
                messages.success(request,'Thanks for registering!',
                                extra_tags='alert alert-success alert-dismissible fade show')
                return redirect('login')
    

    else:
        form=UserRegistration()
    return render(request,'register.html',{'form':form})



def login_user(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request,username=username,password=password)
          
        if user is not None:
            
            login(request, user)
            redirect_url = request.GET.get('next', 'Upload:fileUpload')
            return redirect(redirect_url)
            
                     
        else:
            messages.error(request, "Username or password is not correct",
                            extra_tags ='alert alert-warning alert-dismissible fade show')

    return render(request,'login.html')     

templates/FileUpload.html
{% extends 'base.html' %}

{% block content %}
<div style="margin: 20px auto; width: 80%; max-width: 600px; text-align: center;">
    <h2 style="font-size: 24px; margin-bottom: 20px;">Upload File</h2>
    
    {% if messages %}
    <div style="background-color: #f5f5f5; border: 1px solid #ddd; padding: 10px; margin-bottom: 20px;">
        {% for message in messages %}
        <div {% if message.tags %} style="padding: 10px; background-color: #d4edda; border: 1px solid #c3e6cb; color: #155724;" {% endif %}>
            {{ message }}
            <button type="button" style="background-color: transparent; border: none; outline: none; cursor: pointer;" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </div>
    {% endif %}
    
    <form action="{% url 'Upload:fileUpload' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>
            {{ form.files }}
        </p>
        <button type="submit" style="background-color: #007bff; color: #fff; border: none; padding: 10px 20px; font-size: 16px; cursor: pointer;">Upload</button>
    </form>
</div>
{% endblock %}

templates/all_files.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            {% if messages %}
            <div class="alert alert-dismissible alert-success">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <ul>
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Uploaded Files</h3>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        {% for file in files %}
                        <li class="list-group-item">
                            <a href="{% url 'Upload:download_file' file.id %}" style="text-decoration: none;">
                                <i class="fa fa-file-text-o"></i> {{ file.files.name }}
                            </a>
                        </li>
                        {% empty %}
                        <li class="list-group-item text-muted">No files uploaded.</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Poll Me | Polls List</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
        crossorigin="anonymous">



    {% block custom_css %}{% endblock custom_css %}

</head>

<body>
    {% include 'includes/navbar.html' %}

    {% block content %}

    {% endblock content %}


    <!-- All javascript files goes under here    -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>

templates/includes/navbar.html
<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <a class="navbar-brand" href=""><i class="fas fa-book-reader"></i></a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
        aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="">FILE Uploader <span class="sr-only">(current)</span></a>
            </li>

        </ul>
        <div class="navbar-nav ml-auto">


            {% if request.user.is_authenticated %}
           
            
             <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Upload:fileUpload' %}">Upload Files</a>
                </li>

                <li class="nav-item">
                <a class="nav-link" href="{% url 'Upload:all_files' %}">Download Files</a>
                </li>
            

            </ul>
            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>

            {% else %}
            
            
            {% endif %}
        </div>
    </div>
</nav>

templates/login.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            
            <form action="" method="post" >
            
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" name="username" placeholder="Enter Username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" name="password" placeholder="Password">
                </div>
                
                <button type="submit" class="btn btn-primary">Login</button>
                <p>Need an account? <a href="{% url 'accounts:register' %}">Register Here</a></p>
            </form>
        </div>
    </div>
</div>
{% endblock %}